# Generated by Django 4.0.4 on 2022-05-07 09:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Bill',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('amount', models.PositiveIntegerField()),
                ('date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Book_info',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ISBN', models.CharField(max_length=13, unique=True)),
                ('name', models.CharField(max_length=50)),
                ('publisher', models.CharField(max_length=50)),
                ('author', models.CharField(max_length=50)),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('amount', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Guest_bill',
            fields=[
                ('bill_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='system.bill')),
                ('status', models.CharField(choices=[('1', '未付款'), ('2', '已付款')], default='1', max_length=2, verbose_name='状态')),
                ('is_stock', models.BooleanField(default=0)),
            ],
            bases=('system.bill',),
        ),
        migrations.CreateModel(
            name='Stock_bill',
            fields=[
                ('bill_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='system.bill')),
                ('status', models.CharField(choices=[('1', '未付款'), ('2', '已付款'), ('3', '已退货'), ('4', '已到货')], default='1', max_length=2, verbose_name='状态')),
                ('is_stock', models.BooleanField(default=1)),
            ],
            bases=('system.bill',),
        ),
        migrations.CreateModel(
            name='Finance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('bill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='system.bill')),
            ],
        ),
        migrations.AddField(
            model_name='bill',
            name='book',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='system.book_info'),
        ),
        migrations.AddField(
            model_name='bill',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
