# Generated by Django 4.0.4 on 2022-05-07 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='guest_bill',
            name='is_stock',
        ),
        migrations.RemoveField(
            model_name='stock_bill',
            name='is_stock',
        ),
        migrations.AddField(
            model_name='finance',
            name='is_stock',
            field=models.BooleanField(default=1),
        ),
    ]
