# Generated by Django 4.0.4 on 2022-05-07 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0003_alter_stock_bill_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='book_info',
            name='is_active',
            field=models.BooleanField(default=0),
        ),
    ]
