# Generated by Django 4.0.4 on 2022-05-10 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0004_book_info_is_active'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bill',
            name='price',
        ),
        migrations.AddField(
            model_name='stock_bill',
            name='price',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=6),
            preserve_default=False,
        ),
    ]
