# Generated by Django 4.0.4 on 2022-04-22 18:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Userinfo', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='date_joined',
            new_name='date_created',
        ),
        migrations.RemoveField(
            model_name='user',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='user',
            name='is_staff',
        ),
        migrations.RemoveField(
            model_name='user',
            name='last_name',
        ),
    ]
