# Generated by Django 4.0.4 on 2022-04-22 18:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Userinfo', '0004_user_is_active_user_is_staff_alter_user_is_superuser'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='date_created',
        ),
    ]
