# Generated by Django 4.0.4 on 2022-04-23 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Userinfo', '0005_remove_user_date_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='uid',
            field=models.CharField(max_length=10, primary_key=True, serialize=False, verbose_name='工号'),
        ),
    ]
