# Generated by Django 4.0.4 on 2022-04-26 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Userinfo', '0007_remove_user_age_user_birthday'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='birthday',
            field=models.DateField(default='2010-01-01', verbose_name='出生年月'),
        ),
        migrations.AlterField(
            model_name='user',
            name='picture',
            field=models.ImageField(default='avatars/default.jpg', upload_to='avatars', verbose_name='用户头像'),
        ),
    ]
