# Generated by Django 4.0.4 on 2022-04-26 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Userinfo', '0008_alter_user_birthday_alter_user_picture'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='picture',
        ),
        migrations.AddField(
            model_name='user',
            name='avatar',
            field=models.ImageField(default='avatar/default.jpg', upload_to='avatar', verbose_name='头像'),
        ),
    ]
