# Generated by Django 4.0.4 on 2022-04-26 23:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Userinfo', '0009_remove_user_picture_user_avatar'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='nickname',
        ),
        migrations.AddField(
            model_name='user',
            name='realname',
            field=models.CharField(blank=True, max_length=13, null=True, verbose_name='真实姓名'),
        ),
    ]
